import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
const modulePath=process.env.PLAYWRIGHT_MODULE||'C:/Users/DevTrivi/AppData/Local/npm-cache/_npx/9833c18b2d85bc59/node_modules/playwright/index.mjs';
const { chromium }=await import(pathToFileURL(modulePath).href);
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'C:/Users/DevTrivi/AppData/Local/ms-playwright/chromium-1228/chrome-win64/chrome.exe'});
const page=await browser.newPage({viewport:{width:1440,height:1100}});
const errors=[],failures=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failures.push(`${r.status()} ${r.url()}`);});
const check=(condition,name)=>{assert.ok(condition,name);checks.push(name);};
await mkdir('output/lost-area',{recursive:true});
try {
  await page.goto(`${process.env.BASE_URL||'http://127.0.0.1:8080'}/games.html`);
  await page.getByRole('link',{name:/004.*LOST EXPEDITION/}).click();
  await page.waitForFunction(()=>document.querySelector('#loading').hidden);
  await page.evaluate(async()=>{window.expedition=await import('/src/lost.js');window.scrollTo(0,0);});
  check(await page.evaluate(()=>performance.getEntriesByType('resource').some(r=>r.name.endsWith('/foliage-props-v1.png'))),'foliage atlas loaded');
  await page.screenshot({path:'output/lost-area/desktop.png',fullPage:true});
  const x=await page.evaluate(()=>window.expedition.world.player.x);
  await page.keyboard.down('d');await page.waitForTimeout(320);await page.keyboard.up('d');
  check(await page.evaluate(x=>window.expedition.world.player.x>x+30,x),'keyboard movement');
  await page.keyboard.press('Space');await page.waitForTimeout(150);
  check(await page.evaluate(()=>window.expedition.world.player.y<480),'keyboard jump');
  await page.waitForTimeout(800);await page.keyboard.down('s');await page.waitForTimeout(80);
  check(await page.evaluate(()=>window.expedition.world.player.crouch),'keyboard crouch');await page.keyboard.up('s');
  await page.evaluate(()=>{Object.assign(window.expedition.world.player,{x:560,y:512,vy:0,facing:1});});
  await page.keyboard.press('j');await page.waitForTimeout(350);
  check(await page.evaluate(()=>window.expedition.world.powered===1),'keyboard whip awakens relay');
  check(await page.locator('#relays').textContent()==='RELAYS 1 / 3','relay state reaches HUD');
  await page.keyboard.press('m');check(await page.locator('#map').getAttribute('aria-pressed')==='true','map toggle');
  await page.screenshot({path:'output/lost-area/map.png',fullPage:true});await page.keyboard.press('m');
  await page.keyboard.press('p');const time=await page.evaluate(()=>window.expedition.world.time);
  await page.waitForTimeout(180);check(await page.evaluate(t=>window.expedition.world.time===t,time),'pause freezes simulation');await page.keyboard.press('p');
  await page.evaluate(()=>{Object.assign(window.expedition.world.player,{x:820,y:512,crouch:true,vy:0});});
  await page.waitForTimeout(700);await page.screenshot({path:'output/lost-area/crouch.png',fullPage:true});
  check(await page.evaluate(()=>window.expedition.world.player.crouch),'ceiling retains crouch after key release');
  await page.evaluate(()=>{Object.assign(window.expedition.world.player,{x:2700,y:320,crouch:false,vy:0});});
  await page.waitForTimeout(900);await page.screenshot({path:'output/lost-area/vault.png',fullPage:true});
  await page.evaluate(()=>{Object.assign(window.expedition.world.player,{x:549,y:384,crouch:false,vy:0,grounded:true});});
  await page.waitForTimeout(800);await page.keyboard.press('e');await page.waitForTimeout(80);
  check(await page.evaluate(()=>window.expedition.world.memories.has('canopy')),'E discovers canopy memory');
  check(await page.locator('#memories').textContent()==='MEMORIES 1 / 3','memory discovery reaches HUD');
  await page.screenshot({path:'output/lost-area/canopy-memory.png',fullPage:true});
  await page.evaluate(()=>{Object.assign(window.expedition.world.player,{x:1940,y:448,crouch:false,vy:0,grounded:true});});
  await page.waitForTimeout(900);
  check(await page.evaluate(()=>window.expedition.world.player.y===448),'hunter stands on fallen-log bridge');
  await page.screenshot({path:'output/lost-area/forest-bridge.png',fullPage:true});
  await page.locator('#restart').click();check(await page.evaluate(()=>window.expedition.world.powered===0),'new expedition resets progress');
  check(await page.evaluate(()=>window.expedition.world.memories.size===0),'new expedition resets discovered memories');
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.scrollTo(0,0));
  const right=page.getByRole('button',{name:'Move right',exact:true}),bounds=await right.boundingBox();
  const mobileX=await page.evaluate(()=>window.expedition.world.player.x);
  await page.mouse.move(bounds.x+bounds.width/2,bounds.y+bounds.height/2);await page.mouse.down();await page.waitForTimeout(260);await page.mouse.up();
  check(await page.evaluate(x=>window.expedition.world.player.x>x+20,mobileX),'on-screen movement via pointer');
  const releasedX=await page.evaluate(()=>window.expedition.world.player.x);await page.waitForTimeout(160);
  check(await page.evaluate(x=>Math.abs(window.expedition.world.player.x-x)<4,releasedX),'pointer release stops movement');
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile has no horizontal overflow');
  await page.screenshot({path:'output/lost-area/mobile.png',fullPage:true});
  check(errors.length===0,'no browser exceptions');check(failures.length===0,'no failed resources');
  await writeFile('output/lost-area/verification.json',JSON.stringify({checks,errors,failures},null,2));
  console.log(JSON.stringify({checks,errors,failures},null,2));
} finally {await browser.close();}
